<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>false</InvariantGlobalization>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <DocumentationFile>KamtkSchedule.WebApi.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.2" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.1" />
    <PackageReference Include="Quartz.AspNetCore" Version="3.8.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="6.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KamtkSchedule.Application\KamtkSchedule.Application.csproj" />
    <ProjectReference Include="..\KamtkSchedule.Domain\KamtkSchedule.Domain.csproj" />
    <ProjectReference Include="..\KamtkSchedule.Infrastructure\KamtkSchedule.Infrastructure.csproj" />
  </ItemGroup>

</Project>
