// <auto-generated />
using System;
using KamtkSchedule.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KamtkSchedule.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240228164047_InitialChanged")]
    partial class InitialChanged
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KamtkSchedule.Domain.Entities.Pair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CabinetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discipline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PairNumber")
                        .HasColumnType("int");

                    b.Property<int?>("ScheduleDayId")
                        .HasColumnType("int");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("WhoHasAPair")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleDayId");

                    b.ToTable("Pairs");
                });

            modelBuilder.Entity("KamtkSchedule.Domain.Entities.ScheduleDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int?>("ScheduleStaffWeekId")
                        .HasColumnType("int");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleStaffWeekId");

                    b.ToTable("ScheduleDays");
                });

            modelBuilder.Entity("KamtkSchedule.Domain.Entities.ScheduleStaffWeek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("For")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ScheduleWeekId")
                        .HasColumnType("int");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleWeekId");

                    b.ToTable("ScheduleStaffWeeks");
                });

            modelBuilder.Entity("KamtkSchedule.Domain.Entities.ScheduleWeek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Building")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("ScheduleWeeks");
                });

            modelBuilder.Entity("KamtkSchedule.Domain.Entities.Pair", b =>
                {
                    b.HasOne("KamtkSchedule.Domain.Entities.ScheduleDay", null)
                        .WithMany("Pairs")
                        .HasForeignKey("ScheduleDayId");
                });

            modelBuilder.Entity("KamtkSchedule.Domain.Entities.ScheduleDay", b =>
                {
                    b.HasOne("KamtkSchedule.Domain.Entities.ScheduleStaffWeek", null)
                        .WithMany("Days")
                        .HasForeignKey("ScheduleStaffWeekId");
                });

            modelBuilder.Entity("KamtkSchedule.Domain.Entities.ScheduleStaffWeek", b =>
                {
                    b.HasOne("KamtkSchedule.Domain.Entities.ScheduleWeek", null)
                        .WithMany("StaffSchedules")
                        .HasForeignKey("ScheduleWeekId");

                    b.OwnsOne("KamtkSchedule.Domain.Entities.ScheduleDateInfo", "DateInfo", b1 =>
                        {
                            b1.Property<int>("ScheduleStaffWeekId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("ScheduleEndDay")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("ScheduleStartDay")
                                .HasColumnType("datetime2");

                            b1.HasKey("ScheduleStaffWeekId");

                            b1.ToTable("ScheduleStaffWeeks");

                            b1.WithOwner()
                                .HasForeignKey("ScheduleStaffWeekId");
                        });

                    b.Navigation("DateInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("KamtkSchedule.Domain.Entities.ScheduleWeek", b =>
                {
                    b.OwnsOne("KamtkSchedule.Domain.Entities.ScheduleDateInfo", "DateInfo", b1 =>
                        {
                            b1.Property<int>("ScheduleWeekId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("ScheduleEndDay")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("ScheduleStartDay")
                                .HasColumnType("datetime2");

                            b1.HasKey("ScheduleWeekId");

                            b1.ToTable("ScheduleWeeks");

                            b1.WithOwner()
                                .HasForeignKey("ScheduleWeekId");
                        });

                    b.Navigation("DateInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("KamtkSchedule.Domain.Entities.ScheduleDay", b =>
                {
                    b.Navigation("Pairs");
                });

            modelBuilder.Entity("KamtkSchedule.Domain.Entities.ScheduleStaffWeek", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("KamtkSchedule.Domain.Entities.ScheduleWeek", b =>
                {
                    b.Navigation("StaffSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
