// <auto-generated />
using System;
using KamtkSchedule.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KamtkSchedule.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240305175929_Initial_v1.1.0")]
    partial class Initial_v110
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KamtkSchedule.Domain.Entities.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Groups", "dbo");
                });

            modelBuilder.Entity("KamtkSchedule.Domain.Entities.GroupSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("WeeklyScheduleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "GroupId" }, "IX_GroupSchedules_GroupId");

                    b.HasIndex(new[] { "WeeklyScheduleId" }, "IX_GroupSchedules_WeeklyScheduleId");

                    b.ToTable("GroupSchedules", "dbo");
                });

            modelBuilder.Entity("KamtkSchedule.Domain.Entities.Pair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CabinetName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Discipline")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("PairNumber")
                        .HasColumnType("int");

                    b.Property<int?>("ScheduleDayId")
                        .HasColumnType("int");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "GroupId" }, "IX_Pairs_GroupId");

                    b.HasIndex(new[] { "ScheduleDayId" }, "IX_Pairs_ScheduleDayId");

                    b.HasIndex(new[] { "TeacherId" }, "IX_Pairs_TeacherId");

                    b.ToTable("Pairs", "dbo");
                });

            modelBuilder.Entity("KamtkSchedule.Domain.Entities.ScheduleDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int?>("GroupScheduleId")
                        .HasColumnType("int");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "GroupScheduleId" }, "IX_ScheduleDays_GroupScheduleId");

                    b.ToTable("ScheduleDays", "dbo");
                });

            modelBuilder.Entity("KamtkSchedule.Domain.Entities.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Teachers", "dbo");
                });

            modelBuilder.Entity("KamtkSchedule.Domain.Entities.WeeklySchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Building")
                        .HasColumnType("int");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("WeeklySchedules");
                });

            modelBuilder.Entity("KamtkSchedule.Domain.Entities.GroupSchedule", b =>
                {
                    b.HasOne("KamtkSchedule.Domain.Entities.Group", "GroupNavigation")
                        .WithMany("GroupSchedules")
                        .HasForeignKey("GroupId");

                    b.HasOne("KamtkSchedule.Domain.Entities.WeeklySchedule", "WeeklyScheduleNavigation")
                        .WithMany("GroupSchedules")
                        .HasForeignKey("WeeklyScheduleId");

                    b.OwnsOne("KamtkSchedule.Domain.Entities.Owned.ScheduleDateInfo", "DateInfo", b1 =>
                        {
                            b1.Property<int>("GroupScheduleId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("ScheduleEndDay")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("ScheduleStartDay")
                                .HasColumnType("datetime2");

                            b1.HasKey("GroupScheduleId");

                            b1.ToTable("GroupSchedules", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("GroupScheduleId");
                        });

                    b.Navigation("DateInfo")
                        .IsRequired();

                    b.Navigation("GroupNavigation");

                    b.Navigation("WeeklyScheduleNavigation");
                });

            modelBuilder.Entity("KamtkSchedule.Domain.Entities.Pair", b =>
                {
                    b.HasOne("KamtkSchedule.Domain.Entities.Group", "GroupNavigation")
                        .WithMany("Pairs")
                        .HasForeignKey("GroupId");

                    b.HasOne("KamtkSchedule.Domain.Entities.ScheduleDay", "ScheduleDayNavigation")
                        .WithMany("Pairs")
                        .HasForeignKey("ScheduleDayId");

                    b.HasOne("KamtkSchedule.Domain.Entities.Teacher", "TeacherNavigation")
                        .WithMany("Pairs")
                        .HasForeignKey("TeacherId");

                    b.Navigation("GroupNavigation");

                    b.Navigation("ScheduleDayNavigation");

                    b.Navigation("TeacherNavigation");
                });

            modelBuilder.Entity("KamtkSchedule.Domain.Entities.ScheduleDay", b =>
                {
                    b.HasOne("KamtkSchedule.Domain.Entities.GroupSchedule", "GroupScheduleNavigation")
                        .WithMany("ScheduleDays")
                        .HasForeignKey("GroupScheduleId");

                    b.Navigation("GroupScheduleNavigation");
                });

            modelBuilder.Entity("KamtkSchedule.Domain.Entities.WeeklySchedule", b =>
                {
                    b.OwnsOne("KamtkSchedule.Domain.Entities.Owned.ScheduleDateInfo", "DateInfo", b1 =>
                        {
                            b1.Property<int>("WeeklyScheduleId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("ScheduleEndDay")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("ScheduleStartDay")
                                .HasColumnType("datetime2");

                            b1.HasKey("WeeklyScheduleId");

                            b1.ToTable("WeeklySchedules");

                            b1.WithOwner()
                                .HasForeignKey("WeeklyScheduleId");
                        });

                    b.Navigation("DateInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("KamtkSchedule.Domain.Entities.Group", b =>
                {
                    b.Navigation("GroupSchedules");

                    b.Navigation("Pairs");
                });

            modelBuilder.Entity("KamtkSchedule.Domain.Entities.GroupSchedule", b =>
                {
                    b.Navigation("ScheduleDays");
                });

            modelBuilder.Entity("KamtkSchedule.Domain.Entities.ScheduleDay", b =>
                {
                    b.Navigation("Pairs");
                });

            modelBuilder.Entity("KamtkSchedule.Domain.Entities.Teacher", b =>
                {
                    b.Navigation("Pairs");
                });

            modelBuilder.Entity("KamtkSchedule.Domain.Entities.WeeklySchedule", b =>
                {
                    b.Navigation("GroupSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
